
default: &default

    adapter: mysql2
    encoding: utf8
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    host: nextia.mx
    username: admin_nuup
    password: nuup2017 
    port: 3306
    socket: /var/run/mysqld/mysqld.sock
    


development:
  <<: *default
  database: nuup_dev


test:
  <<: *default
  database: nuup_dev

production:
  <<: *default
  database: nuup_dev
  username: admin_nuup
  password: nuup2017